name: My Test Workflow

on:
  workflow_dispatch:

jobs:
  job-1:
    runs-on: ubuntu-24.04
    steps:
      - run: echo "Hello, world!"
      - run: echo "The time is $(date)"
  job-2:
    runs-on: ubuntu-24.04
    steps:
      - run: echo "Hello, world2!"
  job-3:
    runs-on: ubuntu-24.04
    needs:
      - job-1
      - job-2
    steps:
      - run: echo "Hello, world3!"
      - run: echo "Job 3 completed"
  job-4:
    runs-on: ubuntu-24.04
    needs:
      - job-1
      - job-3
    steps:
      - run: echo "Job 4 completed"
